# generate by make_entity.py
# please do NOT edit this file directly.
# edit table.py and regenerate it.

from sqlalchemy import Table, Column, INTEGER, VARCHAR, CHAR, TEXT, DATETIME, Index
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()


class Course(Base):
    __tablename__ = 'course'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True, doc=('list', 'detail'))
    Code = Column('code', VARCHAR(100), doc=('list', 'detail', 'edit'))
    Name = Column('name', VARCHAR(255), doc=('list', 'detail', 'edit'))
    ParentId = Column('parent_id', CHAR(20), doc=('list', 'detail', 'edit'))
    DisplayOrder = Column('display_order', INTEGER, doc=('list', 'detail', 'edit'))
    Comment = Column('comment', TEXT, doc=('detail', 'edit'))
    DeleteAt = Column('delete_at', DATETIME)


class CourseDependency(Base):
    __tablename__ = 'course_dependency'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True, doc=('list', 'detail'))
    BeingDependentId = Column('being_dependent_id', VARCHAR(20), doc=('list', 'detail', 'edit'))
    DependentId = Column('dependent_id', VARCHAR(20), doc=('list', 'detail', 'edit'))
    DeleteAt = Column('delete_at', DATETIME)


class Teacher(Base):
    __tablename__ = 'teacher'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True, doc=('list', 'detail'))
    Code = Column('code', VARCHAR(50), doc=('list', 'detail', 'edit'))
    Name = Column('name', VARCHAR(50), doc=('list', 'detail', 'edit'))
    Unit = Column('unit', VARCHAR(100), doc=('list', 'detail', 'edit'))
    Dept = Column('dept', VARCHAR(100), doc=('list', 'detail', 'edit'))
    Phone = Column('phone', VARCHAR(50), doc=('list', 'detail', 'edit'))
    Email = Column('email', VARCHAR(100), doc=('detail', 'edit'))
    Comment = Column('comment', TEXT, doc=('detail', 'edit'))
    DeleteAt = Column('delete_at', DATETIME)


class TeacherCourse(Base):
    __tablename__ = 'teacher_course'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True, doc=('list', 'detail'))
    TeacherId = Column('teacher_id', CHAR(20), doc=('list', 'detail', 'edit'))
    CourseId = Column('course_id', CHAR(20), doc=('list', 'detail', 'edit'))
    Level = Column('level', INTEGER, doc=('list', 'detail', 'edit'))
    DeleteAt = Column('delete_at', DATETIME)


class NaturalClass(Base):
    __tablename__ = 'natural_class'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True, doc=('list', 'detail'))
    Grade = Column('grade', VARCHAR(10), doc=('list', 'detail', 'edit'))
    BelongToCollege = Column('belong_to_college', VARCHAR(20), doc=('list', 'detail', 'edit'))
    Dept = Column('dept', VARCHAR(50), doc=('list', 'detail', 'edit'))
    Name = Column('name', VARCHAR(100), doc=('list', 'detail', 'edit'))
    StudentCount = Column('student_count', INTEGER, doc=('list', 'detail', 'edit'))
    Comment = Column('comment', TEXT, doc=('detail', 'edit'))
    DeleteAt = Column('delete_at', DATETIME)


class TeachingClass(Base):
    __tablename__ = 'teaching_class'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True, doc=('list', 'detail'))
    Name = Column('name', VARCHAR(100), doc=('list', 'detail', 'edit'))
    IncludeNaturalClassIds = Column('include_natural_class_ids', TEXT, doc=('list', 'detail', 'edit'))
    Comment = Column('comment', TEXT, doc=('detail', 'edit'))
    DeleteAt = Column('delete_at', DATETIME)


class Schedule(Base):
    __tablename__ = 'schedule'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True, doc=('list', 'detail'))
    SubjectId = Column('subject_id', CHAR(20), doc=('list', 'detail', 'edit'))
    Weekday = Column('weekday', INTEGER, doc=('list', 'detail', 'edit'))
    TimeRange = Column('time_range', VARCHAR(50), doc=('list', 'detail', 'edit'))
    CourseId = Column('course_id', CHAR(20), doc=('list', 'detail', 'edit'))
    DeleteAt = Column('delete_at', DATETIME)


class ScheduleSubject(Base):
    __tablename__ = 'schedule_subject'
    DbId = Column('db_id', INTEGER, primary_key=True, autoincrement=True)
    Id = Column('id', CHAR(20), unique=True)
    Name = Column('name', VARCHAR(200))
    DateRange = Column('date_range', TEXT)
    DateExchange = Column('date_exchange', TEXT)
    CourseIds = Column('course_ids', TEXT)
    TeacherIds = Column('teacher_ids', TEXT)
    DeleteAt = Column('delete_at', DATETIME)


